version: '3.4'

networks:
  net_web:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  reverse-proxy:
    image: nginx:latest
    container_name: reverse_proxy
    depends_on:
      - web-app
    ports:
      - '4444:4444'
    volumes:
      - ./proxy-conf/:/etc/nginx/conf.d/
    networks:
      - net_web

  db_server:
    image: mysql:latest
    container_name: mysql_server
    volumes:
      - ./master/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    env_file:
      - database.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - net_web

  db_slave:
    image: mysql:latest
    container_name: mysql_slave
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=slave_db
      - MYSQL_USER=slave
      - MYSQL_PASSWORD=root
    volumes:
      - ./slave/conf/mysql.conf.cnf:/etc/mysql/conf.d/mysql.conf.cnf
    depends_on:
      - db_server
    networks:
      - net_web
  
  setup-slave:
    image: mysql:latest
    container_name: setup-slave
    command: ["sh", "/scripts/init-slave.sh"]
    volumes:
      - ./init-slave.sh:/scripts/init-slave.sh
    environment:
      - MASTER_HOST=mysql_server
      - SLAVE_HOST=mysql_slave
    depends_on:
      - db_server
      - db_slave
    networks:
      - net_web
  
  web-app:
    build: ./groupie-app/
    container_name: web_app
    depends_on:
      - db_server
      - db_slave
      - setup-slave
    ports:
      - '8080:8080'
    env_file:
      - database.env
    environment:
      - MYSQL_SERVER_IP=mysql_server
      - MYSQL_SERVER_PORT=3306
    networks:
      - net_web
  
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - net_web

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - net_web

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - "./monitoring/loki-config.yaml:/etc/loki/loki-config.yaml"
    ports:
      - "3100:3100"
    command: "-config.file=/etc/loki/loki-config.yaml"
    networks:
      - net_web

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - net_web

  promtail:
     image: grafana/promtail:latest
     container_name: promtail
     volumes:
       - "./monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml"
       - "/var/log:/var/log"
     command: "-config.file=/etc/promtail/promtail-config.yaml"
     networks:
       - net_web
